sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker-react' #name of app in aws elastic beanstalk
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-west-2-328592414232'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
